#Configure the Spring Actuator endpoints to require an authenticated user with the MANAGEMENT role
management:
  security:
    roles: MANAGEMENT

---
spring:
  profiles: local-development
  datasource:
    url: ${sbac.jdbc.host}/session
    username: ${sbac.jdbc.user}
    password: ${sbac.jdbc.password}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 32
      minimum-idle: 8
      idle-timeout: 10000
      connectionTestQuery: "SELECT 1"
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  cloud:
    bus:
      enabled: false

#Port defined in TDS_Build:docker-compose.yml
  rabbitmq:
    port: 32846

tds:
  cache:
    enabled: false

management:
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false

#Configure the default Spring Security user with the MANAGEMENT role
security:
  user:
    name: user
    password: password
    role: MANAGEMENT

server:
  port: 8082
  undertow:
    buffer-size: 8192
    io-threads: 4
    worker-threads: 32
    direct-buffers: true

session-service:
  #Assume we're also running a tds-exam-service in "local-development" mode
  exam-url: http://localhost:8081
